### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by mrksnrm** [ph1p/figma-measure#5]
Hi!

Thanks for the great plugin, have been used it quite a lot!
Unfortunately it has not worked couple of last days (probably after Figma's last update), when trying to start plugin, nothing happens.

All the best
Marko

**Comment by ph1p** [comment]
Oh! Thanks for reporting :) I'll work on it and publish an update as soon as I can.

**Comment by ph1p** [comment]
Can you tell me which browser and operating system you use?
It would also be nice if you could write down how you call the plugin.

**Comment by ph1p** [comment]
It thinks I found the bug! I fixed it in version 1.2.3. Thanks for reporting! 
Feel free to reach out, if there is any other problem.

**Comment by mrksnrm** [comment]
Thank for fast feedback!

 

It works again, thank you very much!

 

Couple of questions:

*	When I use plugins, all created elements(tooltip, Lines, Angle) are locked by default (don’t remember it was that way before...). Unlocked elements should be preferred. Or maybe add functionality to set locked/unlocked from plugin settings?
*	Is it somehow possible to measure Auto Layout elements? 

 

Feature request. Would be cool to have same kind of options/settings for Lines as it now are for Tooltip.

 

I’m using Chrome (latest version), Win10 Pro.

 

All the best

Marko

**Comment by ph1p** [comment]
> Thank for fast feedback! It works again, thank you very much! 
You're welcome.

* When I use plugins, all created elements(tooltip, Lines, Angle) are locked by default (don’t remember it was that way before...). Unlocked elements should be preferred. Or maybe add functionality to set locked/unlocked from plugin settings? 
I'm on it! I have locked all these frames, because by selecting all elements, they will be excluded.
I'll add an option and remove the locked state by default. Additionally, I will restructure the measurement group, to keep the layer-tree clean.

> * Is it somehow possible to measure Auto Layout elements? 
Please describe what you want to do. For me, auto-layout is only a frame with this option enabled.

> Feature request. Would be cool to have same kind of options/settings for Lines as it now are for Tooltip. 
I'm on it! :)
